

name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
    steps:
    - uses: actions/checkout@v1
    - name: Install Composer dependencies
      run: php${{ matrix.php }} composer install
    - name: Run tests
      run: php${{ matrix.php }} composer test
